// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IUltraVerifier
 * @notice Interface for the Noir-generated UltraPlonk verifier
 * @dev This interface will be implemented by the auto-generated Verifier.sol
 */
interface IUltraVerifier {
    /**
     * @notice Verifies a zero-knowledge proof
     * @param _proof The proof bytes generated by Noir
     * @param _publicInputs Array of public inputs to the circuit
     * @return True if the proof is valid, false otherwise
     */
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external view returns (bool);
}
